import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vad händer i Uppsala?</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Vad händer i:
        </h1>

        <p className={styles.description}>
          Uppsala, Stationsgatan 50
        </p>

        <p className={styles.description}>
          <small><small>Inom 3 km</small></small><br/>
        </p>

        <div className={styles.slidecontainer}>
          <input type="range" min="1" max="100" value="50" className={styles.slider} id="myRange"/>
        </div>
        <br/>

        <div className={styles["event-list"]}>
          <article className={styles.event}>
            <span><b>Event name</b></span>
            <p>Event description</p>
          </article>

          <article className={styles.event}>
            <span><b>Event name</b></span>
            <p>Event description</p>
          </article>

          <article className={styles.event}>
            <span><b>Event name</b></span>
            <p>Event description</p>
          </article>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>
    </div>
  )
}
